framework:
    cache:
        # Cache par défaut en filesystem
        app: cache.adapter.filesystem
        
        pools:
            # Pools Doctrine en Redis
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 86400
            doctrine.query_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 86400
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 86400
                