doctrine:
    dbal:
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                persistent: true
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                logging: false
                profiling: false

    orm:
        # auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        auto_generate_proxy_classes: false
        proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
        # query_cache_driver:
        #     type: pool
        #     pool: doctrine.system_cache_pool
        # result_cache_driver:
        #     type: pool
        #     pool: doctrine.result_cache_pool

        dql:
            string_functions:
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                RAND: DoctrineExtensions\Query\Mysql\Rand
                IFNULL: DoctrineExtensions\Query\Mysql\IfNull
                WEEKDAY: DoctrineExtensions\Query\Mysql\WeekDay
                YEAR: DoctrineExtensions\Query\Mysql\Year
                NOW: DoctrineExtensions\Query\Mysql\Now
                CAST: DoctrineExtensions\Query\Mysql\Cast
                PI: DoctrineExtensions\Query\Mysql\Pi
                SIN: DoctrineExtensions\Query\Mysql\Sin
                ACOS: DoctrineExtensions\Query\Mysql\Acos
                COS: DoctrineExtensions\Query\Mysql\Cos
                ANY_VALUE: DoctrineExtensions\Query\Mysql\AnyValue
                REGEXP: DoctrineExtensions\Query\Mysql\Regexp
                MATCH_AGAINST: DoctrineExtensions\Query\Mysql\MatchAgainst
                IF: DoctrineExtensions\Query\Mysql\IfElse
                WEEK: DoctrineExtensions\Query\Mysql\Week
                JSON_CONTAINS: DoctrineExtensions\Query\Mysql\JsonContains
                EXTRACT: DoctrineExtensions\Query\Mysql\Extract

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

# when@prod, when@staging:
#     doctrine:
#         orm:
#             auto_generate_proxy_classes: false
#             proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#             query_cache_driver:
#                 type: pool
#                 pool: doctrine.system_cache_pool
#             result_cache_driver:
#                 type: pool
#                 pool: doctrine.result_cache_pool

    # framework:
    #     cache:
    #         pools:
    #             doctrine.result_cache_pool:
    #                 adapter: cache.app
    #                 default_lifetime: 1800
    #                 max_items: 1000
    #             doctrine.system_cache_pool:
    #                 adapter: cache.system
    #                 default_lifetime: 3600
    #                 max_items: 500
