# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
    
    trusted_proxies: '127.0.0.1,::1,172.27.0.1,172.27.0.4'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']

    uid:
        default_uuid_version: 4
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    #esi: true
    #fragments: true
    php_errors:
        log: true

    annotations:
        enabled: false

when@dev:
    framework:
        session:
            handler_id: null
            cookie_secure: auto
            cookie_samesite: lax
            storage_factory_id: session.storage.factory.native

when@test:
    framework:
        test: true
        session:
            handler_id: null
            storage_factory_id: session.storage.factory.mock_file