knp_gaufrette:
    stream_wrapper: ~
    adapters:
        blogPromotionPostThumb_adapter:
            aws_s3:
                service_id: ct_file_store.s3
                bucket_name: '%env(AWS_STORAGE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: promotion
                    acl: public-read
        
        backerLogo_adapter:
            aws_s3:
                service_id: ct_file_store.s3
                bucket_name: '%env(AWS_STORAGE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: backers
                    acl: public-read

        blogPostThumb_adapter:
            aws_s3:
                service_id: ct_file_store.s3
                bucket_name: '%env(AWS_STORAGE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: blog
                    acl: public-read

        programLogo_adapter:
            aws_s3:
                service_id: ct_file_store.s3
                bucket_name: '%env(AWS_STORAGE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: programs
                    acl: public-read

        projectThumb_adapter:
            aws_s3:
                service_id: ct_file_store.s3
                bucket_name: '%env(AWS_STORAGE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: projects
                    acl: public-read    

    filesystems:
        blogPromotionPostThumb_fs:
            adapter: blogPromotionPostThumb_adapter

        backerLogo_fs:
            adapter: backerLogo_adapter

        blogPostThumb_fs:
            adapter: blogPostThumb_adapter

        programLogo_fs:
            adapter: programLogo_adapter

        projectThumb_fs:
            adapter: projectThumb_adapter