# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    loaders:
        s3_loader:
            flysystem:
                filesystem_service: 's3.storage'

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    twig:
        mode: lazy

    default_filter_set_settings: 
        format: webp        

    # configure webp
    webp:
        generate: true
        
    resolvers :
        default :
            flysystem:
                filesystem_service: 's3.storage'
                root_url: '%env(CLOUD_IMAGE_URL)%'
                cache_prefix: 'imagine'
        s3_resolver:
            flysystem:
                filesystem_service: 's3.storage'
                root_url: '%env(CLOUD_IMAGE_URL)%'
                cache_prefix: 'imagine'
    filter_sets :
        # cache : ~
        
        # the name of the "filter set"
        blog_thumb_desktop :
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                thumbnail  : { size : [234, 196], mode : outbound }

        blog_thumb_mobile :
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                thumbnail  : { size : [394, 221], mode : outbound }

        blog_preview :
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                thumbnail  : { size : [399, 268], mode : outbound }

        program_thumb_desktop:
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                thumbnail  : { size : [586, 330], mode : outbound }

        program_thumb_mobile:
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                thumbnail  : { size : [394, 222], mode : outbound }

        program_thumb_mini:
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                scale:
                    dim: [null, 70]

        backer_thumb:
            data_loader: 's3_loader'
            cache: 's3_resolver'
            quality : 75
            filters :
                scale:
                    dim: [null, 70]