framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #    options:
            #        use_notify: true
            #        check_delayed_interval: 60000
            #    retry_strategy:
            #        max_retries: 3
            #        multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            'App\Message\SendNotification': async
            'App\Message\Aid\AidExtractKeyword': async
            'App\Message\Aid\AidPropagateUpdate': async
            'App\Message\Alert\AlertMessage': async
            'App\Message\Alert\AlertResume': async
            'App\Message\Export\MsgSpreadsheetToExport': async
            'App\Message\Log\MsgLogAidSearchTempTransfert': async
            'App\Message\Log\MsgLogAidViewTempTransfert': async
            'App\Message\Reference\ProjectReferenceCountAids': async
            'App\Message\Perimeter\CountyCountBacker': async
            'App\Message\Perimeter\MsgPerimeterCombine': async
            'App\Message\Perimeter\MsgPerimeterImport': async
            'App\Message\Backer\BackerCountAid': async
            'App\Message\SearchPage\SearchPageCountAid': async
            'App\Message\Site\MsgDebugMemory': async
            'App\Message\User\AidsExportPdf': async
