monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: rotating_file
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                max_files: 10
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                excluded_http_codes: [404, 405]
                handler: grouped
            grouped:
                type:    group
                members: [streamed, deduplicated]
            streamed:
                type:  stream
                path:  '%kernel.logs_dir%/%kernel.environment%.log'
                level: error
            deduplicated:
                type:    deduplication
                handler: symfony_mailer
            symfony_mailer:
                type:         symfony_mailer
                from_email:   '%env(EMAIL_FROM)%'
                to_email:     '%env(EMAIL_SUPER_ADMIN)%'
                subject:      'An Error Occurred! %%message%%'
                level:        critical
                formatter:    monolog.formatter.html
                content_type: text/html
