twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'form/dsfr-theme.html.twig'
        - 'form/custom_types.html.twig'
        - 'form/entity_checkbox_absolute_type.html.twig'
        - 'form/entity_checkbox_group_absolute_type.html.twig'
        - 'form/entity_grouped_type.html.twig'
        - 'form/text_length_count_type.html.twig'
        - 'form/url_click_type.html.twig'
        - 'form/image_field_preview.html.twig'

when@test:
    twig:
        strict_variables: true
