vich_uploader:
    db_driver: orm

    mappings:
        blogPromotionPostThumb:
            uri_prefix: /promotion
            upload_destination: '%kernel.project_dir%/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
