vich_uploader:
    # db_driver: orm

    # mappings:
    #     blogPromotionPostThumb:
    #         uri_prefix: /promotion
    #         upload_destination: '%kernel.project_dir%/'
    #         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    db_driver: orm
    storage: gaufrette
    mappings:
        blogPromotionPostThumb:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: blogPromotionPostThumb_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        backerLogo:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: backerLogo_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        blogPostThumb:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: blogPostThumb_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        programLogo:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: programLogo_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        projectThumb:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: projectThumb_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        searchPageLogo:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: searchPageLogo_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        searchPageMetaImage:
            inject_on_load: true
            uri_prefix: "%env(AWS_S3_ENDPOINT_URL)%/%env(AWS_STORAGE_BUCKET_NAME)%"
            upload_destination: searchPageMetaImage_fs
            delete_on_update:   false
            delete_on_remove:   true 
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer