version: '3'
services:
    apache:
        build: .docker/apache
        container_name: at_apache
        ports:
          - "8080:80"
        expose:
          - "8080"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home
        depends_on:
          - php

    mysql:
        image: mysql:8.0.33
        container_name: at_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            --sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: at
            MYSQL_USER: at
            MYSQL_PASSWORD: at
        ports:
          - 42333:3306     

    php:
        build: .docker/php
        container_name: at_php
        volumes:
          - .:/home
        depends_on:
          - mysql