version: '3'
services:
    apache:
        build: .docker/apache
        container_name: at_apache
        ports:
          - "8080:80"
        expose:
          - "8080"
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home
        depends_on:
          - php

    mysql:
        image: mysql:8.0.33
        container_name: at_mysql
        volumes:
            #- .docker/mysql/my.cnf:/var/lib/mysql
            - .docker/data/db:/var/lib/mysql
        command:
            --sql_mode=only_full_group_by
            #- "--default-authentication-plugin=mysql_native_password"
            #- "--lower_case_table_names=1"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: at
            MYSQL_USER: at
            MYSQL_PASSWORD: at
        ports:
          - 42333:3306     

    php:
        build: .docker/php
        container_name: at_php
        volumes:
          - .:/home
        depends_on:
          - mysql